FROM frappe/erpnext:v15.12.2
ADD target/ozone-1.0.0-SNAPSHOT/distro/binaries/erpnext/scripts /opt/erpnext/scripts
ADD target/ozone-1.0.0-SNAPSHOT/distro/configs/erpnext/initializer_config /opt/erpnext/configs
